remote_theme: jekyll/minima
title: Contemplations
description: "This world is but a canvas to our imagination"
author: "Zach Gruber"

minima:
  skin: dark
  social_links:
    twitter: realzachgruber
    instagram: zach.gruber
    
google_analytics: G-987541C0Q2

baseurl: ""
url: "https://zach-gruber.com"

header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

plugins: 
  - jekyll-feed
