remote_theme: jekyll/minima
title: Contemplations
description: Keep an eye out for updates
author: "Zach Gruber"

minima:
  skin: dark
  
baseurl: ""
url: "https://zach-gruber.com"

twitter_username: realzachgruber
instagram_username: zach.gruber

header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

plugins: 
  - jekyll-feed
